name: flutter_sudoku
description: A new Flutter project of sudoku.
publish_to: "none"
version: 1.0.6+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  google_fonts: ^4.0.1
  double_back_to_close: ^2.0.0
  vibration: ^1.7.6
  shimmer: ^3.0.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  modal_bottom_sheet: ^2.1.2
  table_calendar: ^3.0.7
  introduction_screen: ^3.0.2
  sqflite: ^2.1.0+1
  path: ^1.8.2
  just_audio: ^0.9.30
  logger: ^1.1.0
  envied: ^0.3.0
  flutter_slidable: ^3.0.0
  sticky_headers: ^0.3.0+2
  badges: ^3.0.2
  get_it: ^7.2.0
  url_launcher: ^6.1.9
  package_info_plus: ^4.0.0
  flutter_deep_links: ^0.0.2
  app_common_flutter:
    git:
      url: https://github.com/huhx/app_common_flutter
      ref: main
  flex_color_scheme: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/sound/
    - assets/svg/
